version: '3.9'

services:

  web:
    container_name: my-awesome-app-bwk-prod
    image: brennanknopf/my-awesome-app-bwk:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules